version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_net

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - laravel_net

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

volumes:
  dbdata:

networks:
  laravel_net:
    driver: bridge
